### ISSUE TITLE
KeyError when using custom image models

### ISSUE THREAD

**Issue by briaguya** [torchbox/wagtail-grapple#10]
In [get_image_type()](https://github.com/torchbox/wagtail-grapple/blob/fe2196914bcc5222147e6efaea4d627873eb914e/grapple/types/images.py#L134) the registry only has `WagtailImage` in it, which leads to a KeyError when using custom image models as described in the [wagtail custom image documentation](http://docs.wagtail.io/en/v2.5.1/advanced_topics/images/custom_image_model.html)

**Comment by NathHorrigan** [comment]
This is fixed in the latest version @briaguya. Thanks for pointing this out :+1:

**Comment by briaguya** [comment]
That is great news! I’ll try updating my branch to use the latest!
