### ISSUE TITLE
Snippet in StreamField

### ISSUE THREAD

**Issue by emil19** [torchbox/wagtail-grapple#131]
Hello!

It seems like SnippetChooserBlock isn't working like i would initially have expected in a GraphQLStreamfield.

As far as i can tell by reading the source code, allowing accessing the snippet's graphql_fields in a GraphQLStreamfield has not 
in any way been implemented. Like it would when a PageChooserBlock is accessed.

Example:

```graphql
{
  # This works outside of the streamfield
  snippets {
    ... on Person {
      name
    }
  }


  pages {
    ... on HomePage {
      # body is a GraphQLStreamfield
      body {
        ... on SnippetChooserBlock {
          # Snippet is a string, which is not what i would expect.
          snippet
          # Expected behaviour (like PageChooserBlock) that doesn't work:
          snippet {
            ... on Person {
              name
            }
          }
          
        }
        # On PageChooserBlock it works as I expected.
        ... on PageChooserBlock {
          page {
            ... on BlogPostPage {
              attr
            }
          }
        }
      }
    }
  }
}
```

Am i missing something important that would allow me to do something like this, or something that would provide similar functionality?

If not, is it something that would be considered being added to a future version?

**Comment by tbrlpld** [comment]
Hi @emil19, I have not worked with snippets and Grapple yet, but did you see [this example in the docs](https://wagtail-grapple.readthedocs.io/en/latest/general-usage/model-types.html#grapple.models.GraphQLSnippet) 

```python
class BookPage(Page):
    advert = models.ForeignKey(
        'demo.Advert',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    graphql_fields = [
        GraphQLSnippet('advert', 'demo.Advert'),
    ]

    content_panels = Page.content_panels + [
        SnippetChooserPanel('advert'),
    ]

@register_snippet
class Advert(models.Model):
    url = models.URLField(null=True, blank=True)
    text = models.CharField(max_length=255)

    graphql_fields = [
        GraphQLString('url'),
        GraphQLString('text'),
    ]

    panels = [
        FieldPanel('url'),
        FieldPanel('text'),
    ]

    def __str__(self):
        return self.text
```

Is you snippet registered with the `@register_snippet` decorator?

**Comment by zerolab** [comment]
Had a look. This is because of it is defined as a `graphene.String` field - https://github.com/GrappleGQL/wagtail-grapple/blob/master/grapple/types/streamfield.py#L460

Not yet entirely sure how to tackle it as I suspect we may have a dependency issue as `SnippetObjectType` is a `graphene.Union` that declares the types based on snippet models in the registry.
And even though the StreamField blocks registry update happens after that of models/snippets, the `Union` approach makes it trickier to sort out. Will try to look more into it

**Comment by kbayliss** [comment]
I think this is closed by https://github.com/torchbox/wagtail-grapple/pull/256

**Comment by zerolab** [comment]
#256 indeed fixes snippet chooser blocks.
