### ISSUE TITLE
Correct GraphQL field for wagtail RichTextField

### ISSUE THREAD

**Issue by sks444** [torchbox/wagtail-grapple#200]
```python
from wagtail.core.fields import RichTextField

@register_snippet
class TestSnippet(models.Model):
    title = models.CharField(max_length=50)
    description = RichTextField(
        blank=True
    )

    panels = [
        FieldPanel('title'),
        FieldPanel('description'),
    ]

    graphql_fields = [
        GraphQLString('title', required=True),
        GraphQLString('description', required=True),
    ]
```

I have been using `GraphQLString` for wagtail `RichTextField` which doesn't seem to be the most accurate way..as Richtext field output should ideally be passed through richtext method for the rendered content. E.g. In template there is richtext filter and [expand_db_html](https://github.com/wagtail/wagtail/blob/571b9e1918861bcbe64a9005a4dc65f3a1fe7a15/wagtail/core/rich_text/__init__.py#L24) method.

One example is when using apostrophe `'`  inside richtext fields, it returns code instead of the string. 

```shell
In [62]: object.text
Out[62]: '<p data-block-key="t4jac">dc csdc &#x27;This is the string&#x27;</p>'

```

**Comment by sks444** [comment]
Thanks @zerolab,

Do we want this to be handled in `GraphQLString` itself?

For testing purposes I added this bit of code to the [model_resolver](https://github.com/GrappleGQL/wagtail-grapple/blob/554cb2d5d253bffd4213fbfb4fb751351ccc7a29/grapple/actions.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L170)..

```python
        cls_field = getattr(instance, field.field_source)
        if field.field_type.of_type == graphene.String:
            cls_field = render_to_string(
                "wagtailcore/richtext.html",
                {"html": expand_db_html(cls_field)}
            )
```

It still returns the apostrophe `'` as code `&#x27;` in the API 🤔

**Comment by zerolab** [comment]
@sks444 this would need to be handled withing `GraphQLString`. 
Worth coordinating with #204. Need to set aside some time to look into the additional encoding.

**Comment by timmysmalls** [comment]
Or a GraphQLRichText model? I'm not sure if what's the most elegant way to go about it? I could implement either and create a MR.

**Comment by zerolab** [comment]
#259 ensures the `RichTextBlock`'s `rawValue` is always the non-rendered one.

Additionally it adds a new `RICHTEXT_FORMAT` setting defaulting to "html", which both `RichTextField` and `RichTextBlock` respect.

Opted to steer away from a `GraphQLRichText` since it did not make sense as such
