### ISSUE TITLE
`RichTextField` returns internal markup while `RichTextBlock` returns browser-ready HTML

### ISSUE THREAD

**Issue by isolationism** [torchbox/wagtail-grapple#204]
First, a hat tip to all the developers working on this project; thank you for all you have done.

I encountered this one today. The issue can be described thus:

```python
class ExamplePage(HeadlessPreviewMixin, Page):
    body = RichTextField()
    stream_body = StreamField([
        ('paragraph', RichTextBlock()),
        ...
    ])
    graphql_fields = [
        GraphQLString("body"),
        GraphQLStreamfield("stream_body"),
    ]
```

In the result of my GraphQL query for the `ExamplePage` object described above, the `body` field will be in Wagtail's [Rich Text Internals](https://docs.wagtail.io/en/stable/extending/rich_text_internals.html#rich-text-internals) format, which allows the Gatsby client to interpolate objects like images correctly. This is good!

Unfortunately, the `stream_body` field is returned in browser-ready HTML, which is not so good, at least for my purposes — ideally I'd like the resolver to return the actual `raw_value` for `RichText` objects as the property name suggests. The current implementation returns what I would describe as a rendered or interpolated value.

I'm not sure what the expected behaviour _should_ be, but I was able to patch the issue trivially by adding an additional condition to `types.streamfield.StreamFieldInterface.resolve_raw_value()` as follows:

```python
    def resolve_raw_value(self, info, **kwargs):
        if isinstance(self, blocks.StructValue):
            # This is the value for a nested StructBlock defined via GraphQLStreamfield
            return serialize_struct_obj(self)
        elif isinstance(self.value, dict):
            return serialize_struct_obj(self.value)
        # per https://docs.wagtail.io/en/stable/extending/rich_text_internals.html#data-format
        # RichTextBlock.value is converted to browser HTML; this change returns the "internal source"
        # so we can parse and mark-up client-side using the same logic as for `RichTextField`
        elif isinstance(self.value, RichText):
            return self.value.source


        return self.value
```

I'm not sure if this is the desired behaviour or not, but this would amount to a breaking change if existing code expects to carry forward the current, heterogeneous rendering approach between these two similar objects.

Can anyone from the project chime in? I'd be happy to submit a PR with the code above if the maintainers consider this a defect.

**Comment by zerolab** [comment]
@isolationism thank you for the detailed issue description.

There are two things here:
1. `RichTextField` and `RichTextBlock` produce inconsistent results
2. The output of these fields is subject to individual needs (e.g. see #200)

My gut reaction was: `raw_value` should output the field/block value with the unprocessed rich text internals, whereas the normal output should produce browser-ready markup. That does add more complexities as to the post-processing, so why not add a setting that controls the output on both `RichTextField` and `RichTextBlock`?

**Comment by zerolab** [comment]
#259 ensures the `RichTextBlock`'s `rawValue` is always the non-rendered one.

Additionally it adds a new `RICHTEXT_FORMAT` setting defaulting to "html", which both `RichTextField` and `RichTextBlock` respect
