### ISSUE TITLE
ERROR: test_properties_on_saved_example_document (example.tests.test_grapple.DocumentsTest)

### ISSUE THREAD

**Issue by dopry** [torchbox/wagtail-grapple#244]
When running the example tests for main, 44d9cec3766107c82556dc3d315c1ffe2f4dc999, I get the following error. 

```
======================================================================
ERROR: test_properties_on_saved_example_document (example.tests.test_grapple.DocumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\...\wagtail-grapple\example\example\tests\test_grapple.py", line 828, in tearDown
    self.example_document.file.delete()
  File "C:\...\wagtail-grapple\example\venv\lib\site-packages\django\db\models\fields\files.py", line 107, in delete
    self.storage.delete(self.name)
  File "C:\...\wagtail-grapple\example\venv\lib\site-packages\django\core\files\storage.py", line 318, in delete
    os.remove(name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\...\\wagtail-grapple\\example\\media\\documents\\example_6030QSD.txt'
```

**Comment by zerolab** [comment]
@dopry you do need to provide more context to this.
I see this is on Windows, but it is unclear how you're running the tests and so on. They work fine in the CI/locally for me

**Comment by dopry** [comment]
here are the instructions to reproduce...

1. windows 10/python 3.10/bash
2. `cd example`
3. `python -m venv ./venv`
4. `. ./venv/Scripts/activate`
5. `pip install -r requirements.txt`
6. `python manage.py test`

I'm pretty much running the tests as directed by the instructions in only a virtual environment but on windows 10. NTFS is simply more strict about deleting files that are in use. In Linux, you can generally remove a file even if another process has it open.
