### ISSUE TITLE
`N*M + 1` problem when fetching image renditions

### ISSUE THREAD

**Issue by Tijani-Dia** [torchbox/wagtail-grapple#264]
When we fetch multiple image renditions using the `srcSet` parameter on image queries, we end up having an `N * M + 1` situation, where `N` is the total number of images to retrieve renditions for and `M` is the number of renditions to generate.

I've opened a draft PR with a test which confirms this behaviour here: #263.

**Comment by zerolab** [comment]
We could make use of https://docs.wagtail.org/en/latest/releases/4.0.html#image-renditions-can-now-be-prefetched-by-filter for Wagtail 4.0+
