### ISSUE TITLE
StreamField RichText

### ISSUE THREAD

**Issue by mansrz** [torchbox/wagtail-grapple#27]
Hi, 
I got an error on GraphQLStreamfield when i use "RichText"  field

Error:
![DeepinScreenshot_select-area_20191019144147](https://user-images.githubusercontent.com/4426200/67150599-38400980-f27f-11e9-88af-d2c5fd853482.png)

Possible Solution:
![DeepinScreenshot_select-area_20191019151105](https://user-images.githubusercontent.com/4426200/67150858-c4076500-f282-11e9-8db9-f7b3b66b6e24.png)

**Comment by mansrz** [comment]
this is my code:

![image](https://user-images.githubusercontent.com/4426200/67218647-56774800-f3ec-11e9-91bd-57327249b09c.png)

Field in Page
![image](https://user-images.githubusercontent.com/4426200/67218662-5c6d2900-f3ec-11e9-916b-4b43b1713e5d.png)

**Comment by NathHorrigan** [comment]
Hi @mansrz,

Could you post your GraphQL query please?

When querying streamfield data you can do the following:
```
body {
    ...on RichTextBlock {
          value
    }
}
```

**Comment by mansrz** [comment]
Hi, @NathHorrigan 
`
{
  pages{
    ..on HomePage{
      example_content{
        rawValue
      }
    }
  }
}
`

**Comment by NathHorrigan** [comment]
Hi @mansrz,

Your question has made me realise I need to update the docs (badly, task for today/tomorrow). In your struct block definition do the following:

```
from grapple.helpers import register_streamfield_block

@register_streamfield_block
class ExampleBlock(blocks.StructBlock):
  title = blocks.TextBlock(...)
  ... rest of your fields here...

  graphql_fields = [
    GraphQLString('title'),
    ... rest of your fields here...
  ]
```

This will generate a GraphQL Streamfield type that you can use like so:

```
{
  pages {
    ...on HomePage {
      example_content {
        ...on ExampleBlock {
          title
        }
      }
    }
  }
}
```

_Side Note: I'd recommend copying and pasting code into Github Issues instead of images as it makes it easier for me to read and refactor your code like I did above_
