### ISSUE TITLE
grapple vs wagtail-grapple

### ISSUE THREAD

**Issue by dopry** [torchbox/wagtail-grapple#297]
Initially I foundy myself confused by the difference between grapple and wagtail grapple.  I had to pip install wagtail-grapple, but then import grapple in my code.  It would be nice if the package only had one canonical name.

**Comment by engAmirEng** [comment]
I think it's good actually, it improves the developer's understanding of the matter and since there are tons of material for grapple, finding help is going to be nicer for them

**Comment by dopry** [comment]
@engAmirEng are you saying you feel two canonical names helps developers, or that you would prefer grapple as the canonical name?

**Comment by engAmirEng** [comment]
@dopry Oh shoot, sorry, I miss wrote grapple instead of graphene, I meant there are tons of online material in the title of graphene plus I think referencing the standard graphene classes and attrs in the grapple name space just for the sake of naming just sounds wrong

**Comment by dopry** [comment]
I'm not proposing changing the name altogether and grapple is not graphene by a long shot. There is a lot of behavior backed in above and beyond graphene. The only thing I'm proposing is choosing one of grapple or wagtail-grapple to refer to the package instead of using both.

**Comment by zerolab** [comment]
we cannot refer to the package as grapple outside of imports. e.g. https://pypi.org/project/grapple/ is taken by a crypto-related package.

I don't see a massive issue with calling the package `wagtail-grapple`, but import from grapple. There are plenty of Python/Django precendents (e.g. `python-dateutil`). Granted, I may be biased :D

**Comment by dopry** [comment]
the existence of  https://pypi.org/project/grapple/ should be reason enough to update the namespace to wagtail-grapple. The moment someone wants to use wagtail-grapple and grapple in the same project there will be a problem. .  It's just good manners not to use a namespace someone else has already reserved.

**Comment by zerolab** [comment]
On one hand it is a tricky one as it will introduce quite the breaking change which I am not sure I necessarily want to push onto other developers (imports, settings etc). At least not yet 🤔 And https://pypi.org/project/grapple/ has last had a release almost 8.5 years ago

On the other hand it would be explicitly `wagtail_grapple`. 

Would love to hear other people's thoughts

**Comment by engAmirEng** [comment]
Not sure if I get a vote but I'm with @dopry

**Comment by dopry** [comment]
Just because @tinybike  hasn't made a release in 8 years doesn't mean they don't have the rightful claim on the namespace. If we want to continue to use the namespace, maybe we should reach out to @tinybike and ask?

**Comment by tinybike** [comment]
Sorry, just saw this -- I had forgotten all about grapple.  It isn't maintained and almost certainly doesn't work any more.  I'd be happy to delete it from pypi if that's something you guys still want.

**Comment by zerolab** [comment]
Thank you for getting back to us, @tinybike 
I think it is best to make use of [PEP 541](https://peps.python.org/pep-0541/) via https://github.com/pypi/support/issues. Will open an issue there, referencing this issue.

**Comment by zerolab** [comment]
Update, having re-read PEP 541, and we had a message from you @tinybike, we should solve this ourselves.

@tinybike any chance you could transfer it to me (https://pypi.org/user/dan.braghis/)? and I will yank the previous releases as well as update the readme to link to wagtail-grapple.

Thank you

**Comment by tinybike** [comment]
Hello @zerolab sure it's no problem.  I just added you as an owner and it says the invite is pending.  Happy grappling!

**Comment by dopry** [comment]
@tinybike 🎉 🎉  Thank You  🎉 🎉
