### ISSUE TITLE
querying for "custom_rendition_property" in the example, results in error

### ISSUE THREAD

**Issue by engAmirEng** [torchbox/wagtail-grapple#318]
"Cannot return null for non-nullable field CustomImageRendition.customRenditionProperty." is the result of querying the "**custom_rendition_property**" while we have this:
https://github.com/torchbox/wagtail-grapple/blob/1bd7972a2c683a610c90be6c7d05dd067ae2eb35/example/images/models.py#L24-L28

**Comment by engAmirEng** [comment]
Even in #312 this behavior continues to exist, I don't understand why

**Comment by zerolab** [comment]
Fix in #337
