### ISSUE TITLE
Tests are failing on master (wagtailmedia)

### ISSUE THREAD

**Issue by jafacakes2011** [torchbox/wagtail-grapple#32]
We depend on https://github.com/torchbox/wagtailmedia and this is causing test issues with supporting Wagtail 2.7.0.

This will be fixed when Wagtailmedia has the following PRs merged:
 -  [ ] https://github.com/torchbox/wagtailmedia/pull/63
 -  [ ] https://github.com/torchbox/wagtailmedia/pull/71

**Comment by zerolab** [comment]
wagtailmedia has a new release and master allows installing Wagtail 2.7
