### ISSUE TITLE
Installation error using poetry

### ISSUE THREAD

**Issue by ArthurJahn** [torchbox/wagtail-grapple#323]
I'm having the following error when specifying the following dependency on my `pyproject.toml`
``` python
[tool.poetry.dependencies]
# ...
wagtail-grapple = {extras = ["channels"], version = "^0.19.2"}
```
when running poetry install, I get the following error 

```
Updating dependencies
Resolving dependencies... (0.6s)

Because no versions of graphene-django match >3,<4
 and graphene-django (3.0.0) depends on graphql-core (>=3.1.0,<4), graphene-django (>=3,<4) requires graphql-core (>=3.1.0,<4).
And because graphql-ws (0.4.4) depends on graphql-core (>=2.0.0,<3.0.0), graphene-django (>=3,<4) is incompatible with graphql-ws (0.4.4).
And because wagtail-grapple (0.19.2) depends on both graphene-django (>=3,<4) and graphql-ws (0.4.4), wagtail-grapple is forbidden.
So, because no versions of wagtail-grapple match >0.19.2 and sp-cms depends on wagtail-grapple (>=0.19.2), version solving failed.

```
Any thoughts?

Thanks!

**Comment by zerolab** [comment]
Sorry for the silence on this.
The short answer is.. we will likely drop channels support because graphene-wes does not work with graphql-core/graphene-django 3.x

**Comment by ArthurJahn** [comment]
Thanks for the reply! So the page preview will probably work differently, right? Anyway, we're downgrading to 0.18.1 until we have updates on the matter.

**Comment by zerolab** [comment]
The page preview should work OK without channels, especially with Wagtail 4+ and https://github.com/torchbox/wagtail-headless-preview
