### ISSUE TITLE
Inconsistent error handling in the site query

### ISSUE THREAD

**Issue by estyxx** [torchbox/wagtail-grapple#340]
I've noticed an inconsistency in how wagtail-grapple handles errors for the `site` query, which takes `id` and `hostname` as parameters.

When an incorrect `id` is provided, the query appropriately returns `null`, meaning the requested site does not exist. However, when a non-existent `hostname` is provided, it raises an unhandled `DoesNotExist` exception. This exception subsequently results in a `GraphQLError` that is returned in the "errors" response.

The current implementation adds complexity to differentiating between real unhandled errors and expected behaviours, as it behaves differently based on the input parameter.

From a conceptual standpoint, it seems incorrect to raise an unhandled error when the site does not exist, as it is an expected scenario that can occur in normal operation. 

It would be beneficial for the `site` query to handle these errors consistently across both `id` and `hostname` parameters. This would make error handling more predictable and user-friendly.

**Comment by zerolab** [comment]
Fixed by #342
