### ISSUE TITLE
Add equivalent of wagtailimages_tags.image's "preserve-svg" argument

### ISSUE THREAD

**Issue by jams2** [torchbox/wagtail-grapple#345]
When using Wagtail's `image` template tag, developers can provide a `preserve-svg` argument ([docs](https://docs.wagtail.org/en/stable/topics/images.html#svg-images)). When supplied, this argument will cause Wagtail to limit the filters applied to SVGs to only those that would not require rasterisation - i.e. resize and crop operations. If not supplied, attempting to apply a rasterisation-requiring operation to an SVG will result in an error being raised, as Willow cannot perform the operation.

There is no equivalent to this in `grapple`. If acceptable, I would like to add this functionality. It looks like it would be sufficient to add a new argument to the `rendition` field ([here](https://github.com/torchbox/wagtail-grapple/blob/bf5cd104605e112a57ab26b6ee874076e4991cce/grapple/types/images.py#L73)), and update the `resolve_rendition` method with extra conditional logic ([here](https://github.com/torchbox/wagtail-grapple/blob/bf5cd104605e112a57ab26b6ee874076e4991cce/grapple/types/images.py#L92)).

**Comment by zerolab** [comment]
Notes:
- needs a dummy wrapper for `to_svg_safe_spec()` for Wagtail < 5.
- https://github.com/wagtail/wagtail/commit/9e914dbe877a85559d49c40f16cd9a2460c22acc breaks mutations using snippets. solution inline the import in the hook registration
