### ISSUE TITLE
Support for Wagtail 2.7

### ISSUE THREAD

**Issue by glensomerville** [torchbox/wagtail-grapple#35]
I know Wagtail 2.7 is quite fresh still, but just wondering whether it would be possible to add support? Pipenv is complaining about incompatible versions in dependencies when trying to install `wagtail-grapple` into a project with Wagtail 2.7.

**Comment by zerolab** [comment]
Opened #36 to address the setup issue. Note that it depends on https://github.com/torchbox/wagtailmedia/pull/63 as well. Will look at speeding up the fix release

**Comment by glensomerville** [comment]
> Opened #36 to address the setup issue. Note that it depends on [torchbox/wagtailmedia#63](https://github.com/torchbox/wagtailmedia/pull/63) as well. Will look at speeding up the fix release

Great, thanks! I got around the issue in dev with `pipenv install --skip-lock` for the time being.

**Comment by zerolab** [comment]
wagtailmedia has a new release, so this should be sorted
