### ISSUE TITLE
Rendition queries using `preserveSvg` should default to `original` renditions for SVGs

### ISSUE THREAD

**Issue by jams2** [torchbox/wagtail-grapple#389]
If I have an image field that may refer to both raster or SVG images, when querying that field I may pass the `preserveSvg` argument, so as to handle the fact that I might have SVGs in the set, and want to return them without error.

Example query:

```graphql
query Image {
  images(offset: 2, limit: 2) {
    title
    id
    rendition(format: "webp", preserveSvg: true) {
      url     
    }
  }
}
```

Example response:

```json
{
  "data": {
    "images": [
      {
        "id": "78",
        "rendition": null,
        "title": "tiger"
      },
      {
        "id": "77",
        "rendition": {
          "url": "https://my-bucket.s3.eu-west-1.amazonaws.com/images/Tsunami_by_hokusai_19th_century.format-webp.webp"
        },
        "title": "Tsunami_by_hokusai_19th_century"
      }
    ]
  },
  "errors": [
    {
      "locations": [
        {
          "column": 5,
          "line": 5
        }
      ],
      "message": "No valid filter specs for SVG. See https://docs.wagtail.org/en/stable/topics/images.html#svg-images for details.",
      "path": [
        "images",
        0,
        "rendition"
      ]
    }
  ]
}
```

As the source image for "tiger" is an SVG, it cannot be converted to webp. This [causes an error](https://github.com/torchbox/wagtail-grapple/blob/460060e6057981851d16addb299e4a1b95d8637f/grapple/types/images.py#L158). In this scenario my expectation would be that I receive an SVG rendition having its original dimensions.

Another scenario is querying with a mix of SVG safe and unsafe operations, e.g. `rendition(width: 100, format: "webp", preserveSvg: true)`. In this case I would expect to receive any SVGs as width 100 renditions, alongside the other webp renditions.

Perhaps an `excludeSvg` flag would be useful too - to exclude any SVG images from the returned set.

**Comment by jams2** [comment]
As we [don't support an argument for requesting the "original" rendition](https://github.com/torchbox/wagtail-grapple/blob/460060e6057981851d16addb299e4a1b95d8637f/grapple/types/images.py#L42), the `to_svg_safe_spec` might return the empty string, which would cause this error to be thrown. Providing `original` as a boolean arg would be another way to deal with this.

**Comment by zerolab** [comment]
ah, d'oh! you're right.
I am torn between checking that filter_specs is empty and setting it to `original`, and adding the `original` boolean arg because the latter opens a can of worms.. and then we need to support variations etc etc. Happy to be convinved otherwise

**Comment by jams2** [comment]
The former makes sense to me, and is in line with the current behaviour of raster image renditions which I think is fairly intuitive.

**Comment by zerolab** [comment]
https://github.com/torchbox/wagtail-grapple/releases/tag/v0.25.1
