### ISSUE TITLE
resolve_value missing from EmbedBlock

### ISSUE THREAD

**Issue by rachelhsmith** [torchbox/wagtail-grapple#395]
When using the value field of an EmbedBlock in a query, it errors with `"Cannot return null for non-nullable field EmbedBlock.value."`

**Steps to reproduce:**

1. Define a StructBlock with an EmbedBlock field and register it with @register_streamfield_block

```
from wagtail.embeds import blocks as embeds_blocks

@register_streamfield_block
class EmbedStructBlock(blocks.StructBlock):
    embed = embeds_blocks.EmbedBlock()
```

2. Register the field for GraphQL

```
from grapple.types import streamfield as grapple_streamfield

    graphql_fields = [
        grapple_streamfield.EmbedBlock(),
    ]
```

3. Use this EmbedStructBlock in a StreamField of a Page model and execute a GraphQL query which requests ‘value’ on the embed field

```
… on EmbedStructBlock {
	testEmbed {
		value
	}
}
```

Switching the `resolve_raw_value` method of the `EmbedBlock` to `resolve_value` has solved this issue for me in the project I am currently working on

```
    def resolve_value(self, info, **kwargs):
        if isinstance(self, EmbedValue):
            return self
        return StreamFieldInterface.resolve_raw_value(info, **kwargs)
```

Should `resolve_raw_value` actually be `resolve_value`?

**Comment by kbayliss** [comment]
Thanks, @rachelhsmith.

The `EmbedBlock` doesn't have a `raw_value` field:

```
class EmbedBlock(graphene.ObjectType):
    value = graphene.String(required=True)
    url = graphene.String(required=True)
    embed = graphene.String()
    raw_embed = graphene.JSONString()
```

_(Source: https://github.com/torchbox/wagtail-grapple/blob/main/grapple/types/streamfield.py#L349C1-L353C38)_

so the naming of the `resolve_raw_value` method is indeed a mistake, and should be updated as you've suggested.

A MR to resolve this (ideally accompanied by test(s)) would be welcome.

**Comment by JakubMastalerz** [comment]
I'm starting work on this :)
