### ISSUE TITLE
Wagtail release 2.6rc1

### ISSUE THREAD

**Issue by jafacakes2011** [torchbox/wagtail-grapple#4]
```
ERROR: wagtail-grapple 0.1.2 has requirement wagtail<2.6,>=2.5, but you'll have wagtail 2.6rc1 which is incompatible.
```

Release: https://pypi.org/project/wagtail/2.6rc1/
Notes: https://docs.wagtail.io/en/latest/releases/2.6.html

I can't see a reason that we shouldn't support 2.6, I say we bump the `<2.6` to `<2.7`

**Comment by zerolab** [comment]
Can you please open a PR?

**Comment by jafacakes2011** [comment]
This has been handled as part of:
https://github.com/torchbox/wagtail-grapple/commit/ad22212664f6d018bc436e3f404389b7b7bf4830
