### ISSUE TITLE
base64 and tracedSVG are not part of ImageObjectType

### ISSUE THREAD

**Issue by SamuelTaylor001** [torchbox/wagtail-grapple#71]
Using the guide, it does not seem that Base64 or SVG exists within the object that defines images types. The documentation section in question is linked here: https://wagtail-grapple.readthedocs.io/en/latest/general-usage/graphql-types.html?highlight=tracedSvg%3A%20String%20base64%3A#imageobjecttype

The query:
``` GraphQl
{
  pages {
    ... on ExamplePage {
      title
      image {
        src
        base64
      } 
    }
  }
}
```

The output:
``` GraphQl
{
  "errors": [
    {
      "message": "Cannot query field \"base64\" on type \"ImageObjectType\".",
      "locations": [
        {
          "line": 7,
          "column": 9
        }
      ]
    }
  ]
}
```

I believe that this is inhibiting use with [Wagtail-Gatsby](https://github.com/NathHorrigan/wagtail-gatsby)

**Comment by zerolab** [comment]
Looks like that particular piece of functionality was removed in #15, but the docs were missed.

At the same time, https://github.com/NathHorrigan/wagtail-gatsby/blob/master/wagtailgatsby/models.py#L22 indicates that by using `GatsbyImage` as your custom image base, you should be getting `traced_SVG`.

And maybe add `GraphQLString("base64")` to your image model `graphql_fields` declaration  for the base64 representation. @NathHorrigan ?

**Comment by tbrlpld** [comment]
Hm interesting. There seems to be a bit of a conflict between the documentation and the actual project direction. Maybe I am wrong but it looks like @NathHorrigan is moving the Gatsby specific functionality to a separate library. 

Should we maybe update the Grapple documentation, remove the references to this funcitoinality and rather mention the [wagtail-gatsby](https://github.com/NathHorrigan/wagtail-gatsby) project? 

I am happy to make the update and create a pull request.

**Comment by zerolab** [comment]
I removed those references a while ago it seems. Closing
